server:
  port: 9090
  #contextPath: /mts
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  resources:
    cache:
      cachecontrol:
        duration: 1
  boot:
    admin:
      url: http://localhost:18080 # server url
      client:
        url: http://localhost:18080 # server url
        username: admin
        password: admin
        instance:
          metadata:
            user.name: admin
            user.password: admin
          server-url: http://localhost:9090 #client url
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      default_schema: mts
      properties:
        hibernate:
          format_sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: oracle

logging:
    level:
        org:
          hibernate:
            type:
              descriptor:
                sql: trace


management:
  endpoints:
    web:
      path-mapping:
        health: healthcheck
      base-path: /application
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

application:
  title: MTS
  version: 1.0
  formatted-version: 1.0


springdoc:
  swagger-ui:
    path: /apidoc

info:
  contact:
    email: linuxint@gmail.com
    phone: +82