server:
  port: 9090

spring:
  profiles:
    active: dev # 기본 환경을 dev로

  datasource: ##https://www.4te.co.kr/892
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: mts
    password: mts
    MaximumPoolSize: 10
    MinimumIdle: 5
    MaxLifetime: 1200000
    ConnectionTimeout: 20000
    IdleTimeout: 300000
  sql:
#    init:
#      schema-locations:
#        - file:/database/Common/ddl/oracle/table.sql
#      data-locations:
#        - file:/database/Common/dml/oracle/tableData_oracle.sql
    hikari:
      pool-name: pool-oracle
    jpa:
      hibernate:
        ddl-auto: none
      output:
        ansi:
          enabled: always
---
server:
  port: 9090

spring:
  config:
    activate:
      on-profile: local # 환경이름설정

#  jpa:
#    hibernate:
#      ddl-auto: create
##      use-new-id-generator-mappings: false
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: dev

#  jpa:
#    hibernate:
#      ddl-auto: update

---
server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod

#  jpa:
#    hibernate:
#      ddl-auto: none

management:
  health:
    elasticsearch:
      enabled: false
